export default class RelatedPolicyData {
    PolicyData(form,caseNo,selecttdata,productCategory1,reportNo) {
        let data = {
            "additionalDispatchTeacher": false,
            "additionalInsured": false,
            "additionalNoFault": false,
            "appCode": form.appCode,
            "appStatus": form.appStatus,
            "applicationDate": form.applicationDate,
            "backOnEndDate": "",
            "backOnStartDate": "",
            "branchCode": form.branchCode,
            "branchName": form.branchName,
            "caseNo": caseNo,
            "channelCode": form.channelCode,
            "channelName": form.channelName,
            "channelScope": '',
            "cityCode": form.cityCode,
            "countyCode": form.countyCode,
            "createTime": form.createTime,
            "elevatorSeatAddress": selecttdata.elevatorSeatAddress,
            "employedNum": 0,
            "endorsementsNo": '',
            "financeStatus": form.financeStatus,
            "fromSys": '',
            "holderName": form.holderName,
            "id": '',
            "industryName": '',
            "industryType": '',
            "insuredName": form.insuredName,
            "insuredOrganizationCode": '',
            "isDel": false,
            "issueCompanyCode": form.issueCompanyCode,
            "issueCompanyName": form.issueCompanyName,
            "issueDate": form.issueDate,
            "mainBearingCompanyCode": '',
            "mainBearingCompanyName": '',
            "mainCompanyCode": form.mainCompanyCode,
            "mainCompanyName": form.mainCompanyName,
            "majorHazardSources": false,
            "orderCode": form.orderCode,
            "organizationType": form.applicationDate,
            "polEndDate": form.polEndDate,
            "polStartDate": form.polStartDate,
            "polStatus": form.polStatus,
            "policyNo": form.policyNo,
            "premium": form.premium,
            "productCategory1": productCategory1,
            "productCode": form.productCode,
            "productName": form.productName,
            "projectCode": '',
            "projectName": '',
            "provinceCode": form.provinceCode,
            "reducePremium": form.reducePremium,
            "renewPolicyNo": '',
            "renewTimes": '',
            "renewal": form.renewal,
            "reportInfoId": '',
            "reportNo": reportNo,
            "retroactiveDate": '',
            "riskType": productCategory1,
            "risks": [
                {
                "caseNo": caseNo,
                "classCode": '',
                "className": '',
                "code": '',
                "id": '',
                "isDel": '',
                "isSelected": false,
                "name": '',
                "policyNo": form.policyNo,
                "reportNo": reportNo,
                "riskFlag": ""
                }
            ],
            "schoolNature": '',
            "schoolSystem": '',
            "schoolType": '',
            "serviceCode": window.sessionStorage.getItem('userCode'),
            "serviceName": window.sessionStorage.getItem('userName'),
            "theElevatorType": selecttdata.theElevatorType,
            "travelAgency": '',
            "travelAgencyType": '',
            "travelCode": '',
            "updateTime": "",
            "emergencyEquipmentCode":selecttdata.value,
            "ropewayType":selecttdata.value1,
            "ropewayName":selecttdata.label1,
            "elevatorType":selecttdata.theElevatorType,
            "elevatorName":'',
            "identityCardNumber":selecttdata.value2,
            "insuredName":selecttdata.label2,
            "userCode":form.holder ? form.holder.holderCode : '',
            "postName":selecttdata.postName,
            "propertyName":selecttdata.propertyName,

        }
        if(productCategory1=='jz' || productCategory1=='wy'){
            if(form.holderOrInsuredName){
                data.holderName = form.holderOrInsuredName
            } else {
                data.holderName = form.insuredName
            }
            
        }
        return data;
    }
}